
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            exclude: ^tests/
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.3
      hooks:
          - id: flake8
            args:
            - "--max-line-length=88"

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint
          language: system
          types: [python]
          args:
            [
              "-rn",
              "-sn",
              "--generated-members=cv2.",
              "--ignored-modules=tensorflow.compat.v2",
              "--disable=R,C",
              "--ignore-paths=alembic",

              "--init-hook=import sys; sys.path.append('.')"
            ]
